pipeline {
    agent {
        docker { image 'maven:3.9.8-sapmachine-21'
        args '-v$HOME/.m2:/root/.m2'
           }

	}

```

stages {
    stage('Build') {
        steps {
            echo 'Compiling worker app..'

            dir('worker') {
                sh 'mvn compile'
            }
        }
    }

    stage('Test') {
        steps {
            echo 'Running Unit Tests on worker app..'

            dir('worker') {
                sh 'mvn clean test'
            }
        }
    }

    stage('Package') {
        steps {
            echo 'Packaging worker app'

            dir('worker') {
                sh 'mvn package -DskipTests'
            }
        }
    }
}

post {
    always {
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true

        echo 'Building multibranch pipeline for worker is completed..'
    }
}
```

}
